### ISSUE TITLE
TypeError: this.log is not a function

### ISSUE THREAD

**Issue by okonet** [homebridge-squeezebox/homebridge-squeezebox#18]
I've just got my homebridge restarted because 

```
[23/03/2021, 06:21:44] TypeError: this.log is not a function
    at /usr/local/lib/node_modules/homebridge-plugin-squeezebox/index.js:97:9
    at handle (/usr/local/lib/node_modules/homebridge-plugin-squeezebox/node_modules/squeezenode-auth/squeezerequest.js:63:13)
    at /usr/local/lib/node_modules/homebridge-plugin-squeezebox/node_modules/squeezenode-auth/squeezerequest.js:120:13
    at HttpClient.Client._parseResponse (/usr/local/lib/node_modules/homebridge-plugin-squeezebox/node_modules/jayson/lib/client.js:160:18)
    at /usr/local/lib/node_modules/homebridge-plugin-squeezebox/node_modules/jayson/lib/client.js:123:10
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-squeezebox/node_modules/jayson/lib/client/http.js:89:7)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
```

and then it could not start since:

```
[23/03/2021, 06:21:58] [Squeezebox] Getting players...
[23/03/2021, 06:21:58] [Squeezebox] Error: connect ECONNREFUSED 192.168.178.22:9002
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.178.22',
  port: 9002,
  ok: false
}
```

**Comment by rkrug** [comment]
Did you manage to restart it?

`ECONNREFUSED` is related to a refused connection (quick google knowledge...) - you could try to restart homebridge, the server, LMS.

I never had this.

**Comment by okonet** [comment]
I guess so but the point is that it should have done this gracefully. I think the reconnect logic should be more forgiving. Now it takes down the whole home bridge instance. Also the original error is not really related to connection.
