### ISSUE TITLE
Homebridge crashes due to undefined property "power"

### ISSUE THREAD

**Issue by CCRDude** [homebridge-squeezebox/homebridge-squeezebox#2]
My setup is:
- A Debian Jessie machine, running  Logitech Media Server Version: 7.9.0 - 1443165052 @ Wed Sep 30 04:05:33 UTC 2015
- 3x SqueezeBox Radio, 
- 1x older SqueezeBox, 
- 2x iPeng software playback module
- A Raspberry Pi 2 running Debian Jessie  and homebridge with homebridge-squeezebox (and homebridge-fhem, that's why it's on this computer), with homebridge installed within the last few days.

This morning I was wondering why Homekit is not available and noticed this:

```
/usr/lib/node_modules/homebridge-squeezebox/index.js:84
        var on = (Number(res.result.power) == 1);
                                   ^

TypeError: Cannot read property 'power' of undefined
    at /usr/lib/node_modules/homebridge-squeezebox/index.js:84:30
    at handle (/usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:46:13)
    at /usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:54:13
    at Client._parseResponse (/usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client.js:151:18)
    at /usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client.js:112:10
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client/http.js:88:7)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:305:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Might be due to two types of devices not listed yet (the old SqueezeBox, and the iPeng playback module)?

Some kind of error handling in this place would be appreciated :)

**Comment by greebowarrior** [comment]
I've added some extra error handling.
