### ISSUE TITLE
Plugin does not start: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kstaniek** [homebridge-squeezebox/homebridge-squeezebox#3]
/home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/index.js:49
                if (response.ok && response.result.length){
                                                  ^

TypeError: Cannot read property 'length' of undefined
    at /home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/index.js:49:38
    at /home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/server.js:84:13
    at handle (/home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:46:13)
    at /home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:54:13
    at Client._parseResponse (/home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client.js:178:12)
    at /home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client.js:112:10
    at Object.Utils.JSON.parse (/home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/utils.js:275:3)
    at IncomingMessage.<anonymous> (/home/kstaniek/.nvm/versions/node/v4.5.0/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client/http.js:74:22)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by patriot81** [comment]
I had the same issue when no device is connected to the Logitech Media Server.
