### ISSUE TITLE
TypeError: this.log is not a function

### ISSUE THREAD

**Issue by CCRDude** [homebridge-squeezebox/homebridge-squeezebox#5]
Just experienced this morning (got homebridge running in a screen session to look up stuff when it crashes, since it's not yet perfectly stable):

```
/usr/lib/node_modules/homebridge-squeezebox/index.js:92
            this.log(e)
                 ^

TypeError: this.log is not a function
    at /usr/lib/node_modules/homebridge-squeezebox/index.js:92:9
    at handle (/usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:46:13)
    at /usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:54:13
    at Client._parseResponse (/usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client.js:151:18)
    at /usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client.js:112:10
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/node_modules/jayson/lib/client/http.js:88:7)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:305:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
^C
[1]+  Exit 1                  homebridge
```

Updated version just two or three days ago, package.json says version 0.0.5, npm upgrade doesn't see  new version, so I assume it's the latest one.

**Comment by CCRDude** [comment]
Experienced it again two hours ago (just to confirm that it's not a single incidence, but repeated stuff)

**Comment by CCRDude** [comment]
Bad thing is this is crashing my homebridge even if I do not have SqueezeBox in my platforms list :-(

Looking into the code, I found this is a follow-up of my previous issue (#2) about the power state... the "correcting" code is what triggers this.

**Comment by simonrb2000** [comment]
I had similar crashes. I uninstalled it, then used Domoticz to export dimmers that would get/set volume & power via HomeKit app/Siri.

**Comment by CCRDude** [comment]
I'm doing a similar thing now; I have homebridge-fhem in use as well, and use custom fhem devices instead.
