### ISSUE TITLE
not working on initial load

### ISSUE THREAD

**Issue by fireheadman** [homebridge-squeezebox/homebridge-squeezebox#7]
Running Homebridge on MacMini (El Capitan).
Squeezebox is on another server on same network, so replaced 127.0.0.1 with correct IP addr in config.json.

getting this error:

[12/31/2016, 9:44:48 PM] [SmartThings] Fetching Smart Things devices.
[12/31/2016, 9:44:48 PM] [Squeezebox] Initializing Squeezebox platform...
Load homebridge-squeezebox.Squeezebox
/usr/local/lib/node_modules/homebridge-squeezebox/index.js:49
			if (response.ok && response.result.length){
			                                  ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-squeezebox/index.js:49:38
    at /usr/local/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/server.js:84:13
    at handle (/usr/local/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:46:13)
    at /usr/local/lib/node_modules/homebridge-squeezebox/node_modules/squeezenode/squeezerequest.js:54:13
    at HttpClient.Client._parseResponse (/usr/local/lib/node_modules/homebridge-squeezebox/node_modules/jayson/lib/client.js:178:12)
    at /usr/local/lib/node_modules/homebridge-squeezebox/node_modules/jayson/lib/client.js:112:10
    at Object.Utils.JSON.parse (/usr/local/lib/node_modules/homebridge-squeezebox/node_modules/jayson/lib/utils.js:275:3)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-squeezebox/node_modules/jayson/lib/client/http.js:74:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by fireheadman** [comment]
UPDATE:   Looks like your plugin ONLY works for 127.0.0.1 and not for hosts defined by IP address.
Do you have any intentions on allowing remote connections to a squeezebox server?   I run mine on a FreeNAS jail on the same network.

Once I put the IP back to 127.0.0.1, it started up w/o error.

**Comment by simonrb2000** [comment]
I control mine using domoticz. Install that with edomoticz platform then you can control on and off, you can also set the player as a light dimmer, that way you can control the volume via the Native Home App and via Siri.

Cheers.

On 1 Jan 2017, at 04:51, fireheadman <notifications@github.com<mailto:notifications@github.com>> wrote:


UPDATE: Looks like your plugin ONLY works for 127.0.0.1 and not for hosts defined by IP address.
Do you have any intentions on allowing remote connections to a squeezebox server? I run mine on a FreeNAS jail on the same network.

-

**Comment by okonet** [comment]
It's related to this line of code:

https://github.com/greebowarrior/homebridge-squeezebox/blob/a0d39e2c6355cd37665a22fb171c23d7e9e80919/index.js#L52

and in my case it happens after restarting the router. I guess Squeezlite player becomes a new IP or something else is happening so that the server omits the `result`. Not sure why but restarting the player helps.

The fix could be an additional check if the `result` is defined and is of type `Array`.
